### ISSUE TITLE
extreme quality loss when zooming in

### ISSUE THREAD

**Issue by foss1234** [bluaxees/Poricom#7]
this didn't really happen in other versions so i thought to open an issue about this 

![image](https://user-images.githubusercontent.com/101003172/164677612-83215c31-8335-47d3-b6e9-e4aede47a039.png)

**Comment by baselmagdy2** [comment]
Fit to screen

**Comment by bluaxees** [comment]
@baselmagdy2 Are you having the same issue as OP? Did you experience this before v0.3.0?

**Comment by bluaxees** [comment]
Just tested this and the quality loss is very noticeable when using Fit to Height/Fit to Screen mode. For now, you may use Fit to Width while I work on this.

**Comment by bluaxees** [comment]
Hello! The image resolution issue should be fixed in v0.3.1. However, this caused a problem in the zoom behavior which caused the UI to be "jumpy".  See demo below.

I decided to push this changes since I believe image quality should not be compromised. The zoom behavior will stay until I find a better solution.

https://user-images.githubusercontent.com/45705751/164894691-4e4e7a29-2448-4e41-8d15-3b33d1f60df6.mp4
